### ISSUE TITLE
High cpu usage

### ISSUE THREAD

**Issue by leepood** [Derealize/derealize#1]
## Summary

Very high cpu usage, here is the screenshot below

![2621628048909_ pic_hd](https://user-images.githubusercontent.com/1982360/128119584-8250a493-f23d-40c8-ba95-84b3c27b23ba.jpg)

## Env
Host: MacOS 11.5

**Comment by zicjin** [comment]
ok. we need more information.
1. version?
2. editor or studio?
3. Is a project running? Or just opening the derealize application?

If you are running a project using Derealize Studio. Please click the "debug information" button in toolbar to see if there are any exceptions.

**Comment by leepood** [comment]
1. Version: 1.1.4
2. Editor
3. no project running, just open and quit the app

**Comment by elliotreborn** [comment]
Does this problem always appear every time the application is launched?
Sorry, this has never happened in my local testing. You can try upgrading to the latest version and confirm that the problem is reproducible.

**Comment by zicjin** [comment]
This problem should come from electron or its upstream chromium.
https://github.com/electron/electron/pull/29806
https://github.com/Eloston/ungoogled-chromium/issues/315

I upgraded the electron to the latest version 13.1.8, hoping that this kind of problem won't occur again.
Now close issus first. If the problem recurs, please open issus again.
